export const tanlangan_savdo = [
    {
        id: 1,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 2,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 3,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 4,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 5,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 6,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 7,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 8,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 9,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    },
    {
        id: 10,
        images: "../../assets/images/xona.png",
        title: "Apartment for sale",
        description: "London, Oxford St",
        day: "26 November 2020",
        price: "290.000 $",
        icon1: "bx bx-chair",
        num1: "3+1",
        icon2: "fa fa-signal",
        num2: "10",
        icon3: "fa fa-cube",
        num3: "150m2"
    }
]